ARG build_version="latest"

FROM robertslando/zwave2mqtt:4.1.1
# latest is the latest stable major/minor version for this container 

LABEL version="${build_version}" \
      maintainer="rbe-git@t-online.de" \
      description="ZWave to Mqtt connector"

# TODO: run as non-root
# TODO: pass secrets as ENV variables